name: Ruby Gem

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Running tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.7
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Bundle
        run: bundle install
      - name: Rubocop
        run: rubocop
      - name: Run tests
        run: bundle exec rake

  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Build
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7
    - run: bundle install
